#!/usr/local/bin/python

import argparse
import os
import signal
import sys
import time

from boto.utils import get_instance_metadata
from boto.compat import six
import boto.ec2.elb


def _convert_key_to_str(key):
    if isinstance(key, six.text_type):
        # the secret key must be bytes and not unicode to work
        #  properly with hmac.new (see http://bugs.python.org/issue5285)
        return str(key)
    return key

def _get_connection(region, security_token):
    conn = boto.ec2.elb.connect_to_region(region, security_token=security_token)
    return(conn)

def _get_iam_token():
    security_creds = get_instance_metadata(
                timeout=2.0, num_retries=5,
                data='meta-data/iam/security-credentials/')
    if security_creds:
        # I'm assuming there's only one role on the instance profile.
        security = list(security_creds.values())[0]
        return(security['Token'])
    else:
        print("No security credentials available.")
        sys.exit(1)

def deregister_func(lbname, region, instance_id):
    def handler(*args, **kwargs):
        elb = _get_connection(region, _get_iam_token())
        print("Deregistering instance {} from ELB {}".format(instance, lbname))
        elb.deregister_instances(lbname, [instance_id])
        sys.exit(0)
    return handler

def register_instance(lbname, region, instance_id):
    elb = _get_connection(region, _get_iam_token())
    print("Registering instance {} to ELB {}".format(instance, lbname))
    instances = elb.register_instances(lbname, [instance_id])
    print("Remaining instances: " + ",".join(instances))
    return(instances)

# Parse arguments or get from ENV
parser = argparse.ArgumentParser(description='Register the local EC2 instance in an ELB')
parser.add_argument('--lbname', metavar='<NAME>', default=os.environ.get('ELB_NAME'),
                    help='Name of AWS ELB that should be used for registration')
parser.add_argument('--region', metavar='<REGION>', default=os.environ.get('AWS_REGION'),
                    help='AWS region in which the ELB resides')
cargs = parser.parse_args()

# Get instance id
metadata = get_instance_metadata(timeout=2.0, num_retries=5,
            data='meta-data/instance-id')
instance = list(metadata.keys())[0]

# Register the Instance
register_instance(cargs.lbname, cargs.region, instance)

# Deregistration Hooks
deregister = deregister_func(cargs.lbname, cargs.region, instance)
signal.signal(signal.SIGTERM, deregister)
signal.signal(signal.SIGINT, deregister)

while True:
    time.sleep(5)
